apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-services
  namespace: ecommerce
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecommerce-secrets-reader
  namespace: ecommerce-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecommerce-secrets-read
  namespace: ecommerce-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecommerce-secrets-reader
subjects:
- kind: ServiceAccount
  name: ecommerce-services
  namespace: ecommerce
